let n1= prompt('digite o primeiro número: ')
n1= Number(n1)
let n2=prompt('digite o segundo número: ')
n2= Number(n2)
// operações aritmeticas
alert(`${n1} + ${n2} = ${n1 + n2}`)
alert(`${n1} - ${n2} = ${n1 - n2}`)
alert(`${n1} * ${n2} = ${n1 * n2}`)
alert(`${n1} / ${n2} = ${n1 / n2}`)
alert(`${n1} % ${n2} = ${n1 % n2}`)
alert(`${n1} ** ${n2} = ${n1 ** n2}`)